-- SUSPEND ENTIRE TASK TREE
-- root task 
ALTER TASK CRYPTO_DB.TASKS.CLEAN_CRYPTO_PRICES_TASK SUSPEND;

-- child tasks
ALTER TASK CRYPTO_DB.TASKS.UPDATE_WATERMARK_TASK SUSPEND;
ALTER TASK CRYPTO_DB.TASKS.LOAD_DIM_COIN_TASK SUSPEND;
ALTER TASK CRYPTO_DB.TASKS.LOAD_FACT_COIN_PRICES_TASK SUSPEND;
ALTER TASK CRYPTO_DB.TASKS.FACT_MARKET_SNAPSHOT SUSPEND;


-- RESUME ENTIRE TASK TREE
-- child tasks first 
ALTER TASK CRYPTO_DB.TASKS.FACT_MARKET_SNAPSHOT RESUME;
ALTER TASK CRYPTO_DB.TASKS.LOAD_FACT_COIN_PRICES_TASK RESUME;
ALTER TASK CRYPTO_DB.TASKS.LOAD_DIM_COIN_TASK RESUME;
ALTER TASK CRYPTO_DB.TASKS.UPDATE_WATERMARK_TASK RESUME;

-- root task last
ALTER TASK CRYPTO_DB.TASKS.CLEAN_CRYPTO_PRICES_TASK RESUME;