CREATE OR REPLACE TASK CRYPTO_DB.TASKS.UPDATE_WATERMARK_TASK
WAREHOUSE = CRYPTO_WH
AFTER CRYPTO_DB.TASKS.CLEAN_CRYPTO_PRICES_TASK
AS

UPDATE CRYPTO_DB.SILVER.ETL_WATERMARK
SET last_processed_at = (
    SELECT MAX(ingested_at)
    FROM CRYPTO_DB.RAW.CRYPTO_PRICES_RAW
)
WHERE pipeline_name = 'crypto_prices';