CREATE OR REPLACE TASK CRYPTO_DB.TASKS.LOAD_DIM_COIN_TASK
WAREHOUSE = CRYPTO_WH
AFTER CRYPTO_DB.TASKS.CLEAN_CRYPTO_PRICES_TASK
AS 
INSERT INTO CRYPTO_DB.GOLD.DIM_COIN
(
    coin_id
)

SELECT 
    DISTINCT coin_id
FROM CRYPTO_DB.SILVER.CRYPTO_PRICES_CLEAN s
WHERE NOT EXISTS 
    (
        SELECT 1
        FROM CRYPTO_DB.GOLD.DIM_COIN d
        WHERE d.coin_id = s.coin_id
    );