SELECT *
FROM CRYPTO_DB.RAW.CRYPTO_PRICES_RAW
ORDER BY ingested_at DESC
LIMIT 10;
ALTER TASK CRYPTO_DB.SILVER.CLEAN_CRYPTO_PRICES_TASK
SUSPEND;

SELECT COUNT(*)
FROM CRYPTO_DB.RAW.CRYPTO_PRICES_RAW;

SELECT COUNT(*)
FROM CRYPTO_DB.SILVER.CRYPTO_PRICES_CLEAN;

EXECUTE TASK CRYPTO_DB.TASKS.LOAD_DIM_COIN_TASK;
EXECUTE TASK CRYPTO_DB.TASKS.FACT_MARKET_SNAPSHOT

SELECT *
FROM TABLE(CRYPTO_DB.INFORMATION_SCHEMA.TASK_HISTORY())
ORDER BY SCHEDULED_TIME DESC
LIMIT 20;