CREATE DATABASE CRYPTO_DB;

CREATE SCHEMA CRYPTO_DB.RAW;

CREATE WAREHOUSE CRYPTO_WH
WITH 
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60,
AUTO_RESUME=TRUE;


CREATE TABLE CRYPTO_DB.RAW.CRYPTO_PRICES_RAW(
    coin_id VARCHAR,
    price_usd FLOAT,
    market_cap FLOAT,
    volume_24h FLOAT,
    change_24h_pct FLOAT,
    last_updated_at TIMESTAMP_NTZ,
    ingested_at TIMESTAMP_NTZ
);

